import { fontSans } from "@/configs/fonts";
import { siteConfig } from "@/configs/site";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "../styles/globals.css";
import { RadixUIProviders } from "./provider";

export const metadata: Metadata = {
  title: siteConfig.name || "Create Next App",
  description: siteConfig.description || "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.className}>
        <RadixUIProviders
          themeProps={{ attribute: "class", defaultTheme: "light" }}
        >
          <Theme>{children}</Theme>
        </RadixUIProviders>
      </body>
    </html>
  );
}
